export const data = [
    {
        name: "Rib eye a las brasas (400g)",
        price: 350,
        category: "carnes",
        description: "acompañado de vegetales",
    },
    {
        name: "T-Bone a las brasas (400g)",
        price: 350,
        category: "carnes",
        description: "acompañado de vegetales",
    },
    {
        name: "Arrachera a las brasas (400g)",
        price: 350,
        category: "carnes",
        description: "acompañado de vegetales",
    },
    {
        name: "Chorizo al vino",
        price: 120,
        category: "para picar",
        description: "",
    },
    {
        name: "Chistorra a la sidra",
        price: 120,
        category: "para picar",
        description: "",
    },
    {
        name: "Albóndigas chupa dedos",
        price: 120,
        category: "para picar",
        description: "",
    },
    {
        name: "Hongos al ajillo",
        price: 140,
        category: "para picar",
        description: "",
    },
    {
        name: "Papas bravas",
        price: 100,
        category: "para picar",
        description: "",
    },
    {
        name: "Fetuccini Alfredo",
        price: 250,
        category: "pastas",
        description: "con pasta artesanal y camarones",
    },
    {
        name: "Fetuccini a la marinera",
        price: 250,
        category: "pastas",
        description: "con pasta artesanal, almejas, camarones, mejillones, calamar, etc...",
    },
    {
        name: "Camarones al ajillo",
        price: 300,
        category: "mariscos",
        description: "",
    },
    {
        name: "Pulpo a las brasas",
        price: 350,
        category: "mariscos",
        description: "con chimichurri de albahaca acompañado de papas asadas",
    },
    {
        name: "Pulpo a la gallega",
        price: 250,
        category: "mariscos",
        description: "delicia de la cocina española con aceite de oliva y pimentón ahumado",
    },
    {
        name: "Quesadilla de pulpo",
        price: 250,
        category: "mariscos",
        description: "orden de 3",
    },
    {
        name: "Mejillones a la marinera",
        price: 140,
        category: "mariscos",
        description: "exquisitos mejillones salteados en su jugo con ajo, perejil y vino blanco",
    },
    {
        name: "Paella mixta",
        price: 200,
        category: "arroz",
        description: "mariscos, carnes, chorizo y vegetales",
    },
    {
        name: "Paella de mariscos",
        price: 220,
        category: "arroz",
        description: "",
    },
    {
        name: "Ensalada mediterránea",
        price: 150,
        category: "ensalada",
        description: "lechuga, pepino, cebolla, tomate cherry, morrón asado, aderezo de aceite de oliva y balsámico",
    },
    {
        name: "Lechón al horno (entero)",
        price: 3000,
        category: "sobre pedido",
        description: "",
    },
    {
        name: "Cabrito al horno (entero)",
        price: 3000,
        category: "sobre pedido",
        description: "",
    },
    {
        name: "Borrego al horno (entero)",
        price: 3300,
        category: "sobre pedido",
        description: "",
    },
    {
        name: "Leche frita",
        price: 100,
        category: "postres",
        description: "harina con leche y azucar",
    },
    {
        name: "Flan granadino",
        price: 100,
        category: "postres",
        description: "flan en base a almendras y brandy",
    },
]